# This file generates the GitHub Actions matrix.
# esp32c3_devkitm
board:
  - nice_nano

shield:
  - charybdis_left
  - charybdis_right
  - charybdis_dongle
  - settings_reset

format:
  - dongle
  - bt
  - reset

keymap:
  - qwerty

include:
  - board: nice_nano
    shield: charybdis_dongle
    keymap: qwerty
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano
    shield: charybdis_right
    keymap: qwerty
    snippet: zmk-usb-logging
  - board: nice_nano
    shield: charybdis_left
    keymap: qwerty
