# This file generates the GitHub Actions matrix.

board:
  - nice_nano

shield:
  - charybdis_left
  - charybdis_right
  - charybdis_dongle
  - settings_reset

format:
  - dongle
  - reset

keymap:
  - qwerty

include:
  - board: esp32c3_devkitm
    shield: charybdis_dongle
    keymap: qwerty
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
