## Split keyboards
## https://zmk.dev/docs/config/system#split-keyboards
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

## ZMK Studio
## https://zmk.dev/docs/features/studio
CONFIG_ZMK_STUDIO=y
## https://zmk.dev/docs/config/studio
CONFIG_ZMK_STUDIO_LOCKING=y
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=y
CONFIG_ZMK_STUDIO_TRANSPORT_BLE_PREF_LATENCY=5

CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_INPUT_LISTENER=y

## Logging (USB logging enabled via zmk-usb-logging snippet in build.yaml)
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

## RGB Underglow
## https://zmk.dev/docs/config/underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n