CONFIG_ZMK_USB=n # ZMK_USB is only allowed when: not split or, split and role is central (i.e., not left)

## USB Logging (debug only - remove for production builds)
## Plug left half into USB and open the CDC ACM serial port to read logs.
CONFIG_ZMK_USB_LOGGING=y