CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

## Logging (no USB backend on peripheral - messages compiled in only)
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

## RGB Underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n